[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[functions]
  included_files = ["public/data/*.json"]
  external_node_modules = ["google-it"]

[[redirects]]
  from   = "/data/*"
  to     = "/data/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
